AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Process messages on an SQS queue with Lambda
Resources:
  SqsQueueFunction:
    Type: AWS::Serverless::Function
    FunctionName: sqs-queue-lambda
    Properties:
      Handler: index.handler
      CodeUri: src/
      Runtime: nodejs18.x
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SqsQueue.Arn
            BatchSize: 10
  SqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: sqs-queue