AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: REST API
Globals:
  Function:
    Runtime: nodejs18.x
    Environment:
      Variables:
        TABLE_NAME:
          Ref: MembersTable
    MemorySize: 128
    Timeout: 5
Resources:
  MembersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Members
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create.handler
      CodeUri: s3://a-bucket-01234/327fcc1ba687b9d985b55c0a6222bb1e
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: MembersTable
      Events:
        CreateMember:
          Type: Api
          Properties:
            Path: /members
            Method: POST
