AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless::2016-10-31'
Resources:
  LogFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: src/
     