AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: SAM Template

Resources:
  LogFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs18.x
      Handler: index.handler
      CodeUri: src/
      Events:
        LogSchedule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref S3EventBucket
            Events: s3:ObjectCreated:*
        ApiResource:
          Type: Api
          Properties:
            Path: /event
            Method: GET

  S3EventBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: a-bucket-01234x
     