AWSTemplateFormatVersion: '2010-09-09'
Description: Create SNS Topic
Resources:
  SnsTopic: 
    Type: AWS::SNS::Topic
    Properties:
      TopicName: goal-notification
      Subscription:
           - Endpoint: user@postcore.net
             Protocol: email