// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using poststackserver.Data;

#nullable disable

namespace poststackserver.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230322145234_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("poststackserver.Data.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 2,
                            Content = "This is content for post 1.",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "This is content for post 2.",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "This is content for post 3.",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "This is content for post 4.",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "This is content for post 5.",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 7,
                            Content = "This is content for post 6.",
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
