AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Inventory REST API

Globals:
  Function:
    Runtime: nodejs18.x
    Environment:
      Variables:
        TABLE_NAME: !Ref InventoryTable
    MemorySize: 128
    Timeout: 5

Resources:
  MembersTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      TableName: Inventory
      PrimaryKey:
        Name: sku
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1    