// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkWell.API.DbContexts;

#nullable disable

namespace WorkWell.API.Migrations
{
    [DbContext(typeof(JobsDbContext))]
    [Migration("20250903214720_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkWell.API.Entities.Company", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("JobId")
                        .HasColumnType("integer");

                    b.HasKey("Name");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Name = "NewTek Solutions",
                            ContactEmail = "contact@teksolutions.com",
                            ContactPhone = "555-555-5555",
                            Description = "NewTek Solutions is a leading technology company specializing in web development and digital solutions. We pride ourselves on delivering high-quality products and services to our clients while fostering a collaborative and innovative work environment.",
                            JobId = 1
                        },
                        new
                        {
                            Name = "Veneer Solutions",
                            ContactEmail = "contact@loremipsum.com",
                            ContactPhone = "555-555-5555",
                            Description = "Veneer Solutions is a creative agency specializing in digital design and development. Our team is dedicated to pushing the boundaries of creativity and innovation to deliver exceptional results for our clients.",
                            JobId = 2
                        },
                        new
                        {
                            Name = "Dolor Cloud",
                            ContactEmail = "contact@dolorsitamet.com",
                            ContactPhone = "555-555-5555",
                            Description = "Dolor Cloud is a leading technology company specializing in digital solutions for businesses of all sizes. With a focus on innovation and customer satisfaction, we are committed to delivering cutting-edge products and services.",
                            JobId = 3
                        },
                        new
                        {
                            Name = "Alpha Elite",
                            ContactEmail = "contact@adipisicingelit.com",
                            ContactPhone = "555-555-5555",
                            Description = "Alpha Elite is a dynamic startup specializing in digital marketing and web development. We are committed to fostering a diverse and inclusive workplace where creativity and innovation thrive.",
                            JobId = 4
                        },
                        new
                        {
                            Name = "Browning Technologies",
                            ContactEmail = "contact@consecteturadipisicing.com",
                            ContactPhone = "555-555-5555",
                            Description = "Browning Technologies is a rapidly growing technology company specializing in e-commerce solutions. We offer a dynamic and collaborative work environment where employees are encouraged to think creatively and innovate.",
                            JobId = 5
                        },
                        new
                        {
                            Name = "Port Solutions INC",
                            ContactEmail = "contact@ipsumlorem.com",
                            ContactPhone = "555-555-5555",
                            Description = "Port Solutions is a leading technology company specializing in software development and digital marketing. We are committed to providing our clients with cutting-edge solutions and our employees with a supportive and rewarding work environment.",
                            JobId = 6
                        });
                });

            modelBuilder.Entity("WorkWell.API.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "We are seeking a talented Front-End Developer to join our team in Boston, MA. The ideal candidate will have strong skills in HTML, CSS, and JavaScript, with experience working with modern JavaScript frameworks such as React or Angular.",
                            Location = "Boston, MA",
                            Salary = "$70K - $80K",
                            Title = "Senior React Developer",
                            Type = "Full-Time"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Join our team as a Front-End Developer in sunny Miami, FL. We are looking for a motivated individual with a passion for crafting beautiful and responsive web applications. Experience with UI/UX design principles and a strong attention to detail are highly desirable.",
                            Location = "Miami, FL",
                            Salary = "$70K - $80K",
                            Title = "Front-End Engineer (React & Redux)",
                            Type = "Full-Time"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Are you passionate about front-end development? Join our team in vibrant Brooklyn, NY, and work on exciting projects that make a difference. We offer competitive compensation and a collaborative work environment where your ideas are valued.",
                            Location = "Brooklyn, NY",
                            Salary = "$70K - $80K",
                            Title = "React.js Dev",
                            Type = "Full-Time"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Join our team as a Part-Time Front-End Developer in beautiful Pheonix, AZ. We are looking for a self-motivated individual with a passion for creating engaging user experiences. This position offers flexible hours and the opportunity to work remotely.",
                            Location = "Pheonix, AZ",
                            Salary = "$60K - $70K",
                            Title = "React Front-End Developer",
                            Type = "Part-Time"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Exciting opportunity for a Full-Time Front-End Developer in bustling Atlanta, GA. We are seeking a talented individual with a passion for building elegant and scalable web applications. Join our team and make an impact!",
                            Location = "Atlanta, GA",
                            Salary = "$90K - $100K",
                            Title = "Full Stack React Developer",
                            Type = "Full-Time"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Join our team as a Front-End Developer in beautiful Portland, OR. We are looking for a skilled and enthusiastic individual to help us create innovative web solutions. Competitive salary and great benefits package available.",
                            Location = "Portland, OR",
                            Salary = "$100K - $110K",
                            Title = "React Native Developer",
                            Type = "Full-Time"
                        });
                });

            modelBuilder.Entity("WorkWell.API.Entities.Company", b =>
                {
                    b.HasOne("WorkWell.API.Entities.Job", "Job")
                        .WithOne("Company")
                        .HasForeignKey("WorkWell.API.Entities.Company", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("WorkWell.API.Entities.Job", b =>
                {
                    b.Navigation("Company")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
