// <auto-generated />
using System;
using CourseStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CourseStore.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241126181548_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CourseStore.API.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("character varying(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eb57b0d1-7d07-4d1a-81ae-10c2555a78a3"),
                            Description = "Comprehensive overview of the scientific study of thought and behavior",
                            Title = "Introduction to Psychology"
                        },
                        new
                        {
                            Id = new Guid("2de47cda-cbd9-4f00-9e5a-6912c37a6c6e"),
                            Description = "Learn Python - the most popular programming language and for Data Science and Software Development",
                            Title = "Python for Data Science, AI & Development"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
