AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: REST API

Resources: 
  ProductFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Policies:
      Events:
        GetProducts:
          Type: Api
          Properties:
            Path: /products
            Method: GET
        GetProduct:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: GET
        CreateProduct:
          Type: Api
          Properties:
            Path: /products
            Method: POST
        UpdateProduct:
          Type: Api
          Properties:
            Path: /products/{id}
            Method: PUT                      

  Table:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      PrimaryKey:
        Name: id
        Type: String
