AWSTemplateFormatVersion: '2010-09-09'
Description: Create Orders DynamoDB table
Resources:
  OrdersTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Orders
      AttributeDefinitions:
        - AttributeName: 'Username'
          AttributeType: 'S'
        - AttributeName: 'OrderDate'
          AttributeType: 'S'                 
      KeySchema:
        - AttributeName: 'Username'
          KeyType: 'HASH'
        - AttributeName: 'OrderDate'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
