AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Inventory REST API
Globals:
  Function:
    Runtime: nodejs18.x
    Environment:
      Variables:
        TABLE_NAME:
          Ref: InventoryTable
    MemorySize: 128
    Timeout: 5
Resources:
  InventoryTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Inventory
      PrimaryKey:
        Name: sku
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  InventoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: s3://a-bucket-01234/b5be75fb3b6398c2f076a42af839f0c6
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: InventoryTable
      Events:
        GetAllItems:
          Type: Api
          Properties:
            Path: /inventory
            Method: GET
        GetItem:
          Type: Api
          Properties:
            Path: /inventory/{sku}
            Method: GET
  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      CodeUri: s3://a-bucket-01234/b5be75fb3b6398c2f076a42af839f0c6
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: InventoryTable
      Events:
        CreateMember:
          Type: Api
          Properties:
            Path: /inventory
            Method: POST
