AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Write to Kinesis Data Firehose
Parameters:
  PermissionPrincipal:
    Type: String
Resources:
  lambdaToS3:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FirehoseLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::489967615225:role/lambda-basic-execution-role
      Handler: app.handler
      CodeUri: s3://a-bucket-01234/f9022074ce8fc7690281bb49fca75c00
  lambdaUrl:
    Type: AWS::Lambda::Url
    DependsOn: lambdaToS3
    Properties:
      AuthType: AWS_IAM
      TargetFunctionArn:
        Fn::GetAtt:
        - lambdaToS3
        - Arn
  lambdaUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - lambdaToS3
        - Arn
      FunctionUrlAuthType: AWS_IAM
      Action: lambda:InvokeFunctionUrl
      Principal:
        Ref: PermissionPrincipal
  lambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::GetAtt:
        - lambdaToS3
        - Arn
      Action: lambda:InvokeFunction
      Principal:
        Ref: PermissionPrincipal
