AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Write to Kinesis Data Firehose

Resources:
  lambdaToS3:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: FirehoseLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 3
      Role: arn:aws:iam::489967615225:role/lambda-basic-execution-role
      Handler: app.handler
      CodeUri: src/

  lambdaUrl:
    Type: 'AWS::Lambda::Url'
    DependsOn: lambdaToS3
    Properties: 
      AuthType: NONE
      TargetFunctionArn: !GetAtt lambdaToS3.Arn

  lambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt lambdaToS3.Arn
      FunctionUrlAuthType: 'NONE'
      Action: lambda:InvokeFunctionUrl
      Principal: '*'                  