AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ReedApiFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ReedApiFunction
      Handler: lambda_extract.handler
      CodeUri: src/
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lambda-basic-execution-role
      Runtime: python3.12
      Timeout: 30