AWSTemplateFormatVersion: '2010-09-09'
Description: Create AlbumRank DynamoDB table
Resources:
  MyTable: 
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AlbumRank
      AttributeDefinitions:
        - AttributeName: 'UserId'
          AttributeType: 'N'
        - AttributeName: 'Title'
          AttributeType: 'S'                 
      KeySchema:
        - AttributeName: 'UserId'
          KeyType: 'HASH'
        - AttributeName: 'Title'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1          
      GlobalSecondaryIndexes:
        - IndexName: AlbumTitleIndex
          KeySchema:
            - AttributeName: Title
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
                 - 'Ranking'
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1                  